# Generated by Django 5.2.3 on 2025-06-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matakuliah', models.CharField(max_length=100)),
                ('dosen', models.CharField(max_length=100)),
                ('hari', models.CharField(max_length=20)),
                ('tanggal', models.DateField()),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField()),
                ('ruangan', models.CharField(max_length=50)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
